#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CM.Droid.Resource", IsApplication=true)]

namespace CM.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int ab_background = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ab_bottom_shadow_1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ab_bottom_shadow_2 = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int action_bar_title_color = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int btn_bg_color = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int btn_bg_shadow_color = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int main_background = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int xam_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int xam_dark_blue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int xam_gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int xam_light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int xam_purple = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int btn_corner_radius = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_bg_inactive = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bg_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_bg_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int discrete_shadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dummy_avatar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monoandroidsplash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int user_default_avatar = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int description = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int doB = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int email = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int error = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int fullName = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int listViewTeacher = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int password = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int phoneNumber = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int registBtn = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int signInBtn = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int textViewDescription = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int textViewDoB = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textViewEmail = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int textViewPhoneNumber = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int thumbnail = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CourseView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_Course = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_Teacher = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListTeacherView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StudentView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TeacherView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060007
			public const int GreenButton = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int XamActionBarStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int XamActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int XamActionBarTitleStyle = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int XamSubtitleText = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int XamTitleText = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
